services:
  db:
    image: mysql:8.0
    container_name: konta_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: konta_db
      MYSQL_USER: konta_user
      MYSQL_PASSWORD: konta_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
