# CONFIGURACIÓN DE BASE DE DATOS
# Le decimos que vaya a localhost (Docker) puerto 3306
spring.datasource.url=jdbc:mysql://localhost:3306/konta_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=konta_user
spring.datasource.password=konta_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIÓN DE JPA (EL TRADUCTOR)
# Actualiza las tablas automáticamente si cambias el código
spring.jpa.hibernate.ddl-auto=update
# Nos muestra las consultas SQL en la consola (útil para aprender)
spring.jpa.show-sql=true
